title: Data Visualization Guidebook
description: Overview of Data Viz Best Practices! 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

